/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notes with optional pagination and filtering. */
        get: operations["listNotes"];
        put?: never;
        /** Create a new note. */
        post: operations["createNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single note by path. */
        get: operations["getNote"];
        /** Update a note (supports optimistic concurrency via If-Match). */
        put: operations["updateNote"];
        post?: never;
        /** Delete a note. */
        delete: operations["deleteNote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full-text search across notes. */
        get: operations["searchNotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the knowledge graph (nodes and links). */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an attachment file. */
        post: operations["uploadAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        NoteListItem: {
            path: string;
            title: string;
            checksum: string;
            tags: string[];
            /** Format: date-time */
            updated_at: string;
        };
        NoteDetail: {
            path: string;
            title: string;
            content: string;
            checksum: string;
            tags: string[];
            frontmatter?: {
                [key: string]: unknown;
            } | null;
            backlinks: string[];
            /** Format: date-time */
            updated_at: string;
        };
        NoteListResponse: {
            notes: components["schemas"]["NoteListItem"][];
            total: number;
        };
        CreateNoteRequest: {
            path: string;
            content: string;
        };
        UpdateNoteRequest: {
            content: string;
        };
        SearchResult: {
            path: string;
            title: string;
            snippet: string;
        };
        SearchResponse: {
            results: components["schemas"]["SearchResult"][];
        };
        GraphNode: {
            id: string;
            title?: string;
        };
        GraphLink: {
            source: string;
            target: string;
        };
        GraphResponse: {
            nodes: components["schemas"]["GraphNode"][];
            links: components["schemas"]["GraphLink"][];
        };
        AttachmentResponse: {
            filename: string;
            size: number;
            url: string;
        };
    };
    responses: {
        /** @description Bad request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict (duplicate or checksum mismatch). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Relative path to the note (e.g. folder/note.md). */
        NotePath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listNotes: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                tag?: string;
                sort?: "updated_at" | "title" | "path";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of notes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteListResponse"];
                };
            };
        };
    };
    createNote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoteRequest"];
            };
        };
        responses: {
            /** @description Note created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relative path to the note (e.g. folder/note.md). */
                path: components["parameters"]["NotePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Note detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateNote: {
        parameters: {
            query?: never;
            header?: {
                /** @description SHA-256 checksum for optimistic concurrency control. */
                "If-Match"?: string;
            };
            path: {
                /** @description Relative path to the note (e.g. folder/note.md). */
                path: components["parameters"]["NotePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoteRequest"];
            };
        };
        responses: {
            /** @description Note updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relative path to the note (e.g. folder/note.md). */
                path: components["parameters"]["NotePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Note deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    searchNotes: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Graph data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
        };
    };
    uploadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Attachment uploaded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
